; Laboratorio 4: María José Rojas Mosquera y Orlando Velásquez Granda
; Codigo platformio.ini

[env:az-delivery-devkit-v4]
platform = espressif32
board = az-delivery-devkit-v4
framework = espidf
monitor_speed = 115200

board_build.esp-idf.sdkconfig_path = sdkconfig.defaults
build_flags = 
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BT_NIMBLE_ENABLED=1
